
export const USER_LOGIN_REQUESTED = "USER_LOGIN_REQUESTED";
export const USER_LOGIN_SUCCEEDED = "USER_LOGIN_SUCCEEDED";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";

export const USER_SIGNUP_REQUESTED = "USER_SIGNUP_REQUESTED";
export const USER_SIGNUP_SUCCEEDED = "USER_SIGNUP_SUCCEEDED";
export const USER_SIGNUP_FAILED = "USER_SIGNUP_FAILED";

export const USER_LOGOUT_REQUESTED = "USER_LOGOUT_REQUESTED";

export const USER_UPDATE_REQUESTED = "USER_UPDATE_REQUESTED";
export const USER_UPDATE_SUCCEEDED = "USER_UPDATE_SUCCEEDED";
export const USER_UPDATE_FAILED = "USER_UPDATE_FAILED";

